export const TEXT = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

Morbi tincidunt augue interdum velit euismod in pellentesque massa. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero.

Lacus luctus accumsan tortor posuere ac ut consequat. Feugiat in ante metus dictum at tempor commodo. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Semper auctor neque vitae tempus quam pellentesque nec nam. Posuere ac ut consequat semper viverra. Netus et malesuada fames ac turpis. Odio morbi quis commodo odio. Mauris cursus mattis molestie a iaculis at erat. Urna duis convallis convallis tellus id interdum velit laoreet id. Et netus et malesuada fames ac turpis egestas integer. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Platea dictumst vestibulum rhoncus est. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Aliquam vestibulum morbi blandit cursus risus at. Quis eleifend quam adipiscing vitae proin.

Vel elit scelerisque mauris pellentesque pulvinar pellentesque. Volutpat commodo sed egestas egestas fringilla. Lobortis elementum nibh tellus molestie nunc non blandit. Varius sit amet mattis vulputate enim nulla aliquet. Enim sed faucibus turpis in eu mi bibendum. Maecenas sed enim ut sem viverra aliquet eget sit amet. Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Consequat ac felis donec et odio. Ut enim blandit volutpat maecenas volutpat blandit. Amet massa vitae tortor condimentum lacinia. Viverra aliquet eget sit amet tellus cras adipiscing enim eu. Natoque penatibus et magnis dis parturient montes nascetur. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis nisl. Nulla facilisi morbi tempus iaculis. Scelerisque in dictum non consectetur a erat nam at. Vitae auctor eu augue ut lectus arcu bibendum. Diam maecenas ultricies mi eget mauris pharetra et ultrices neque. Id velit ut tortor pretium viverra suspendisse.

Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Scelerisque eleifend donec pretium vulputate. Auctor eu augue ut lectus arcu bibendum at varius. Sagittis id consectetur purus ut faucibus. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Pellentesque eu tincidunt tortor aliquam nulla facilisi. Mattis molestie a iaculis at erat pellentesque adipiscing. Vel risus commodo viverra maecenas accumsan lacus vel. Ut ornare lectus sit amet est placerat in. Fusce id velit ut tortor pretium viverra. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Pellentesque habitant morbi tristique senectus et netus et. Eu feugiat pretium nibh ipsum consequat nisl vel pretium. Phasellus vestibulum lorem sed risus ultricies tristique nulla. Ultricies tristique nulla aliquet enim tortor.

Adipiscing vitae proin sagittis nisl rhoncus mattis. Pharetra pharetra massa massa ultricies mi. Ac felis donec et odio pellentesque. Est velit egestas dui id ornare arcu odio. Justo nec ultrices dui sapien. Vel pharetra vel turpis nunc eget lorem dolor sed viverra. Quam elementum pulvinar etiam non quam lacus. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Non consectetur a erat nam at. Congue quisque egestas diam in arcu cursus euismod quis. Nullam ac tortor vitae purus faucibus ornare. Vel quam elementum pulvinar etiam non quam lacus. Leo vel fringilla est ullamcorper eget. Quis risus sed vulputate odio ut enim blandit. Semper eget duis at tellus. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh sit. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Orci porta non pulvinar neque laoreet suspendisse interdum consectetur.

Egestas diam in arcu cursus euismod quis viverra. Massa sapien faucibus et molestie ac feugiat sed. Euismod nisi porta lorem mollis aliquam ut porttitor leo. Amet purus gravida quis blandit turpis cursus in. At elementum eu facilisis sed odio. Pretium lectus quam id leo. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi. Tortor consequat id porta nibh venenatis cras sed felis. Enim lobortis scelerisque fermentum dui faucibus in ornare. Tincidunt lobortis feugiat vivamus at augue. Sed augue lacus viverra vitae. Eu ultrices vitae auctor eu augue. Molestie at elementum eu facilisis. Laoreet id donec ultrices tincidunt arcu non sodales. Commodo viverra maecenas accumsan lacus vel. Eget nulla facilisi etiam dignissim. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Ut aliquam purus sit amet luctus venenatis lectus magna. Quis hendrerit dolor magna eget est lorem ipsum.
`;
