export const VIEW = {
  START: 'start',
  OVERVIEW: 'overview',
  GLOBAL_SETTINGS: 'global-settings',
  ABOUT: 'about',
  DONATE: 'donate',
  DONATE_ONETIME: 'donate/onetime',
  DONATE_REGULAR: 'donate/regular',
  LOCAL_SETTINGS: 'local-settings',
  WORKOUT: 'workout',
  TIME_WORKOUT: 'time',
  REPS_WORKOUT: 'reps',
  FREE_WORKOUT: 'free',
  STATISTICS: 'statistics',
  EXPLANATION: 'explanation',
} as const;
