export const ACTIONS = {
  SET_GAME_MODE: 'SET_GAME_MODE',
  SET_EXERCISES_DIFFICULTIES: 'SET_EXERCISES_DIFFICULTIES',
  SET_GAME: 'SET_GAME',
  SET_FIRST_FACTOR: 'SET_FIRST_FACTOR',
  START_GAME: 'START_GAME',
  CREATE_REP: 'CREATE_REP',
  PUSH_ANSWER: 'PUSH_ANSWER',
  PAUSE_GAME: 'PAUSE_GAME',
  STOP_WORKOUT: 'STOP_WORKOUT',
};
